Doubanbook:
  data_path: './datasets'
  batch_size_train: 2048 
  batch_size_test: 204800 
  topk: [1, 3, 5, 10, 20, 40, 50, 80, 100] 
  neg_num: 1 

  aug_type: "Noise" 
  embedding_sizes: [64] 
  num_layerss: [3] 

  US_ratios: [0.0] 
  UV_ratios: [0.0] 
  SV_ratios: [0.1] 

  lrs: [1.0e-4] 
  l2_regs: [1.0e-6] 
  c_lambdas: [0.05] 
  c_temps: [0.15] 

  epochs: 200 
  test_interval: 1 